# Schema for the configuration files of the Vartheme BS4.
vartheme_bs4.settings:
  type: theme_settings
  label: 'Vartheme BS4 settings'
  mapping:

    # Library.
    # ----------------------------
    bootstrap_barrio_library:
      type: text
      label: 'Load library'

    # Container.
    # ----------------------------
    bootstrap_barrio_fluid_container:
      type: integer
      label: 'Fluid container'

    # Region.
    # ----------------------------
    bootstrap_barrio_region_clean_navigation:
      type: integer
      label: 'Clean wrapper for Navigation region'
    bootstrap_barrio_region_class_navigation:
      type: text
      label: 'Classes for Navigation region'
    bootstrap_barrio_region_clean_navigation_collapsible:
      type: integer
      label: 'Clean wrapper for Navigation (Collapsible) region'
    bootstrap_barrio_region_class_navigation_collapsible:
      type: text
      label: 'Classes for Navigation (Collapsible) region'
    bootstrap_barrio_region_clean_header:
      type: integer
      label: 'Clean wrapper for Top Bar region'
    bootstrap_barrio_region_class_header:
      type: text
      label: 'Classes for Top Bar region'
    bootstrap_barrio_region_clean_hero_slider:
      type: integer
      label: 'Clean wrapper for Media Hero Slider region'
    bootstrap_barrio_region_class_hero_slider:
      type: text
      label: 'Classes for Media Hero Slider region'
    bootstrap_barrio_region_clean_highlighted:
      type: integer
      label: 'Clean wrapper for Highlighted region'
    bootstrap_barrio_region_class_highlighted:
      type: text
      label: 'Classes for Highlighted region'
    bootstrap_barrio_region_clean_help:
      type: integer
      label: 'Clean wrapper for Help region'
    bootstrap_barrio_region_class_help:
      type: text
      label: 'Classes for Help region'
    bootstrap_barrio_region_clean_content:
      type: integer
      label: 'Clean wrapper for Content region'
    bootstrap_barrio_region_class_content:
      type: text
      label: 'Classes for Content region'
    bootstrap_barrio_region_clean_sidebar_first:
      type: integer
      label: 'Clean wrapper for Primary region'
    bootstrap_barrio_region_class_sidebar_first:
      type: text
      label: 'Classes for Primary region'
    bootstrap_barrio_region_clean_sidebar_second:
      type: integer
      label: 'Clean wrapper for Secondary region'
    bootstrap_barrio_region_class_sidebar_second:
      type: text
      label: 'Classes for Secondary region'
    bootstrap_barrio_region_clean_footer:
      type: integer
      label: 'Clean wrapper for Footer region'
    bootstrap_barrio_region_class_footer:
      type: text
      label: 'Classes for Footer region'
    bootstrap_barrio_region_clean_page_top:
      type: integer
      label: 'Clean wrapper for Page top region'
    bootstrap_barrio_region_class_page_top:
      type: text
      label: 'Classes for Page top region'
    bootstrap_barrio_region_clean_page_bottom:
      type: integer
      label: 'Clean wrapper for Page bottom region'
    bootstrap_barrio_region_class_page_bottom:
      type: text
      label: 'Classes for Page bottom region'

    # Sidebar position.
    # ----------------------------
    bootstrap_barrio_sidebar_position:
      type: text
      label: 'Sidebar position'
    bootstrap_barrio_content_offset:
      type: integer
      label: 'Content offset'

    # Sidebar first layout.
    # ----------------------------
    bootstrap_barrio_sidebar_collapse:
      type: integer
      label: 'Sidebar collapse'
    bootstrap_barrio_sidebar_first_width:
      type: integer
      label: 'Sidebar first width'
    bootstrap_barrio_sidebar_first_offset:
      type: integer
      label: 'Sidebar first offset'

    # Sidebar second layout.
    # ----------------------------
    bootstrap_barrio_sidebar_second_width:
      type: integer
      label: 'Sidebar second width'
    bootstrap_barrio_sidebar_second_offset:
      type: integer
      label: 'Sidebar second layout'

    # Buttons.
    # ----------------------------
    bootstrap_barrio_button:
      type: integer
      label: 'Convert input submit to button element'
    bootstrap_barrio_button_size:
      type: text
      label: 'Default button size'
    bootstrap_barrio_button_outline:
      type: integer
      label: 'Button with outline format'

    # Navbar.
    # ----------------------------
    bootstrap_barrio_navbar_container:
      type: text
      label: 'Navbar width container'
    bootstrap_barrio_navbar_toggle:
      type: text
      label: 'Navbar toggle size'
    bootstrap_barrio_navbar_top_navbar:
      type: integer
      label: 'Navbar top is navbar'
    bootstrap_barrio_navbar_top_position:
      type: text
      label: 'Navbar top position'
    bootstrap_barrio_navbar_top_color:
      type: text
      label: 'Navbar top link color'
    bootstrap_barrio_navbar_top_background:
      type: text
      label: 'Navbar top background color'
    bootstrap_barrio_navbar_position:
      type: text
      label: 'Navbar position'
    bootstrap_barrio_navbar_color:
      type: text
      label: 'Navbar link color'
    bootstrap_barrio_navbar_background:
      type: text
      label: 'Navbar background color'

    # Messages.
    # ----------------------------
    bootstrap_barrio_messages_widget:
      type: text
      label: 'Messages widget'

    # Form.
    # ----------------------------
    bootstrap_barrio_radio:
      type: text
      label: 'Radio widget'
    bootstrap_barrio_checkbox:
      type: text
      label: 'Checkbox widget'
    bootstrap_barrio_select:
      type: text
      label: 'Select widget'
    bootstrap_barrio_file:
      type: text
      label: 'File widget'

    # Affix.
    # ----------------------------
    bootstrap_barrio_navbar_top_affix:
      type: integer
      label: 'Affix navbar top'
    bootstrap_barrio_navbar_affix:
      type: integer
      label: 'Affix navbar'
    bootstrap_barrio_sidebar_first_affix:
      type: integer
      label: 'Affix sidebar first'
    bootstrap_barrio_sidebar_second_affix:
      type: integer
      label: 'Affix sidebar first'

    # Scrollspy.
    # ----------------------------
    bootstrap_barrio_scroll_spy:
      type: text
      label: 'Scrollspy element ID'

    # Fonts.
    # ----------------------------
    bootstrap_barrio_google_fonts:
      type: text
      label: 'Google Fonts combination'

    # Icons.
    # ----------------------------
    bootstrap_barrio_bootstrap_icons:
      type: integer
      label: 'Use Bootstrap icons'
    bootstrap_barrio_icons:
      type: text
      label: 'Icon set'

    # System messages.
    # ----------------------------
    bootstrap_barrio_system_messages:
      type: text
      label: 'System messages color scheme'

    # Tables.
    # ----------------------------
    bootstrap_barrio_table_style:
      type: text
      label: 'Table cell style'
    bootstrap_barrio_table_hover:
      type: integer
      label: 'Hover effect over table cells'
    bootstrap_barrio_table_head:
      type: text
      label: 'Table header color scheme'
